const APP_RELEASE = Object.freeze({
  VERSION: '3.30.2',
  SCHEMA_VERSION: 10,
  CHANNEL: 'STABLE',
  RELEASE_DATE: '2026-09-07'
});

const APP_CONFIG = Object.freeze({
  // ID spreadsheet disimpan oleh installer pada Script Properties.
  // Dengan demikian paket kode yang sama dapat dipakai semua unit tanpa edit Config.gs.
  get SPREADSHEET_ID() {
    return getInstanceSpreadsheetId_();
  },
  TIME_ZONE: 'Asia/Jakarta',
  SHEETS: Object.freeze({
    BERKAS: 'DB_BERKAS',
    ITEM: 'DB_ITEM',
    KLASIFIKASI: 'MASTER_KLASIFIKASI',
    PEMINJAMAN: 'PEMINJAMAN',
    AUDIT: 'AUDIT_LOG',
    SETTINGS: 'SETTINGS',
    HISTORY: 'RIWAYAT_NOMOR',
    RECEIPT: 'PENERIMAAN_ARSIP',
    RECEIPT_ITEM: 'PENERIMAAN_ITEM',
    EMPLOYEE: 'MASTER_PEGAWAI',
    RECEIPT_PRINT_LOG: 'LOG_CETAK_PENERIMAAN',
    LOAN_OUT_INDICATOR_LOG: 'LOG_CETAK_OUT_INDICATOR',
    LOAN_BA_LOG: 'LOG_CETAK_BERITA_ACARA',
    TRANSFER_PROPOSAL: 'USUL_PINDAH',
    TRANSFER_PROPOSAL_DETAIL: 'USUL_PINDAH_DETAIL',
    TRANSFER_PROPOSAL_ITEM: 'USUL_PINDAH_ITEM',
    TRANSFER_OUTBOX: 'OUTBOX_RECORD_CENTER',
    SYSTEM_MIGRATIONS: 'SYSTEM_MIGRATIONS',
    SYSTEM_BACKUPS: 'SYSTEM_BACKUPS',
    SYSTEM_JOBS: 'SYSTEM_JOBS',
    SYSTEM_JOB_QUEUE: 'SYSTEM_JOB_QUEUE',
    SYSTEM_HEALTH: 'SYSTEM_HEALTH_LOG',
    SYSTEM_QUARANTINE: 'SYSTEM_QUARANTINE',
    REPORT_BERKAS: 'DAFTAR BERKAS',
    REPORT_ITEM: 'DAFTAR ISI BERKAS'
  }),
  STATUS: Object.freeze({
    BERKAS_DRAFT: 'DRAFT',
    RETENSI_MENUNGGU_ITEM: 'MENUNGGU ITEM',
    PEMINJAMAN_TERSEDIA: 'TERSEDIA'
  }),
  RETENTION_UNITS: Object.freeze(['TAHUN', 'BULAN']),
  FINAL_DISPOSITIONS: Object.freeze(['MUSNAH', 'PERMANEN', 'DINILAI KEMBALI'])
});
